-- =========================================================
-- MASJID NOOR ISLAM
-- SETUP SUPABASE
-- ADMIN + KEGIATAN + CAMPAIGN DONASI + STORAGE
-- =========================================================


-- =========================================================
-- 1. ADMIN USERS
-- =========================================================

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

drop policy if exists "admin_users_read_own"
on public.admin_users;

create policy "admin_users_read_own"
on public.admin_users
for select
to authenticated
using (auth.uid() = user_id);


-- =========================================================
-- 2. FUNCTION CEK ADMIN
-- =========================================================

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  );
$$;

grant execute on function public.is_admin()
to anon, authenticated;


-- =========================================================
-- 3. KEGIATAN
-- =========================================================

create table if not exists public.kegiatan (
  id bigint generated by default as identity primary key,
  nama_kegiatan text not null,
  hari text,
  jam time,
  deskripsi text
);

alter table public.kegiatan enable row level security;

drop policy if exists "kegiatan_public_read"
on public.kegiatan;

drop policy if exists "kegiatan_admin_insert"
on public.kegiatan;

drop policy if exists "kegiatan_admin_update"
on public.kegiatan;

drop policy if exists "kegiatan_admin_delete"
on public.kegiatan;


create policy "kegiatan_public_read"
on public.kegiatan
for select
to anon, authenticated
using (true);


create policy "kegiatan_admin_insert"
on public.kegiatan
for insert
to authenticated
with check (public.is_admin());


create policy "kegiatan_admin_update"
on public.kegiatan
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());


create policy "kegiatan_admin_delete"
on public.kegiatan
for delete
to authenticated
using (public.is_admin());


-- =========================================================
-- 4. CAMPAIGN DONASI
-- =========================================================

create table if not exists public.campaign_donasi (
  id bigint generated by default as identity primary key,

  judul text not null,

  deskripsi text,

  kategori text not null default 'INFAQ',

  target bigint not null
    check (target > 0),

  terkumpul bigint not null default 0
    check (terkumpul >= 0),

  gambar_url text,

  prioritas boolean not null default false,

  aktif boolean not null default true,

  created_at timestamptz not null default now(),

  updated_at timestamptz not null default now()
);


alter table public.campaign_donasi
enable row level security;


drop policy if exists "campaign_public_read"
on public.campaign_donasi;

drop policy if exists "campaign_admin_insert"
on public.campaign_donasi;

drop policy if exists "campaign_admin_update"
on public.campaign_donasi;

drop policy if exists "campaign_admin_delete"
on public.campaign_donasi;


-- Semua pengunjung boleh membaca campaign
create policy "campaign_public_read"
on public.campaign_donasi
for select
to anon, authenticated
using (true);


-- Hanya admin yang bisa tambah
create policy "campaign_admin_insert"
on public.campaign_donasi
for insert
to authenticated
with check (public.is_admin());


-- Hanya admin yang bisa edit
create policy "campaign_admin_update"
on public.campaign_donasi
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());


-- Hanya admin yang bisa hapus
create policy "campaign_admin_delete"
on public.campaign_donasi
for delete
to authenticated
using (public.is_admin());


-- =========================================================
-- 5. AUTO UPDATE updated_at
-- =========================================================

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


drop trigger if exists update_campaign_updated_at
on public.campaign_donasi;


create trigger update_campaign_updated_at
before update
on public.campaign_donasi
for each row
execute function public.update_updated_at_column();


-- =========================================================
-- 6. STORAGE GAMBAR CAMPAIGN
-- =========================================================

insert into storage.buckets (
  id,
  name,
  public
)
values (
  'campaign-images',
  'campaign-images',
  true
)
on conflict (id)
do update set public = true;


-- =========================================================
-- POLICY STORAGE
-- =========================================================

drop policy if exists "campaign_images_public_read"
on storage.objects;

drop policy if exists "campaign_images_admin_insert"
on storage.objects;

drop policy if exists "campaign_images_admin_update"
on storage.objects;

drop policy if exists "campaign_images_admin_delete"
on storage.objects;


-- Semua orang boleh melihat gambar
create policy "campaign_images_public_read"
on storage.objects
for select
to anon, authenticated
using (
  bucket_id = 'campaign-images'
);


-- Admin boleh upload
create policy "campaign_images_admin_insert"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'campaign-images'
  and public.is_admin()
);


-- Admin boleh update
create policy "campaign_images_admin_update"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'campaign-images'
  and public.is_admin()
)
with check (
  bucket_id = 'campaign-images'
  and public.is_admin()
);


-- Admin boleh hapus
create policy "campaign_images_admin_delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'campaign-images'
  and public.is_admin()
);


-- =========================================================
-- SELESAI
-- =========================================================